name: Node.js Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Get code
      uses: actions/checkout@v1
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i
    - name: Build for production
      run: npm run entry build prod
    - name: Upload bundle analysis for main
      uses: actions/upload-artifact@v2
      with:
        name: analysis-main.html
        path: dist/views/analyze.html
    - name: Upload bundle analysis for 1754
      uses: actions/upload-artifact@v2
      with:
        name: analysis-1754.html
        path: dist/1754/views/analyze.html
